print("Hello World!")
print("Hello again")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
def main():
    print("Hello World")
    print("Hello again")
    print('Yay! Printing')
    print("I'd much rather 'not'.")
    print('I "said" do not touch this.')
main()
